### ISSUE TITLE
sendHttpRequest captures the any connection exception and does not relay it to caller.

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#660]
sendHttpRequest captures the any connection exception and does not relay it to caller.
Is there a better method to do this ?

Simulation condition:
Call httprequest with an invalid domain and the caller is stuck

```java
@Override
public void sendHttpRequest(final HttpRequest request) {

    checkClosed();

    if (trace) {
        logger.debug(sputs("HTTP CLIENT: sendHttpRequest:: \n{}\n", request, "\nparams\n", request.params()));
    }

    final String uri = getURICreateParamsIfNeeded(request);

    final HttpMethod httpMethod = HttpMethod.valueOf(request.getMethod());

    final HttpClientRequest httpClientRequest = httpClient.request(
            httpMethod, uri,
            httpClientResponse -> handleResponse(request, httpClientResponse));

    final MultiMap<String, String> headers = request.getHeaders();

    httpClientRequest.exceptionHandler(error -> {

    if (error instanceof ConnectException) {
        closed.set(true);
        try {
            stop();
        } catch (Exception ex) {
            logger.warn("Unable to stop client " +
                    "after failed connection", ex);
        }
    } else {
        logger.error("Unable to connect to " + host + " port " + port, error);
    }
    });
```

**Comment by SagarN** [comment]
I think a error handler per request is also helpful. This helps to maintain context.
Any request failing will propagate to upstream callbacks.
Right now only ConnectException are returned to caller however, if the Exception is of type VertxException, it does not propagate. I feel , any Exception , should propagated via ` request.getReceiver().errorWithCode`

**Comment by RichardHightower** [comment]
Looks like this was fixed on April 5th or so.
Have you tried a more recent release?

**Comment by SagarN** [comment]
still happening in `qbitVersion = 1.9.4
qbitGroup = io.advantageous.qbit`

**Comment by SagarN** [comment]
I think this is solved partially
